### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by kab3lle** [ryanmcgrath/1.1.1.1-macOS#1]
Hello, This is just what I wanted sadly I cannot get it to run on Mojave please see screenshot

https://i.imgur.com/Gcmdwnq.png

Xcode
`The operation couldn’t be completed. (NEVPNErrorDomain error 1.)`

**Comment by ryanmcgrath** [comment]
On a plane, so bear with me.

I believe this is something that gets fixed after toggling that switch a few times... it's wonky, because:

- NEVPN has a weird bug that doesn't always show, where the order of `loadPreferences` and `savePreferences` matters. For instance, I saw `NEVPNErrorDomain 1` in dev once, and then it wasn't an issue... so there could be better logic there, most likely.
- This was mostly an experiment and I wasn't looking to build a fully functioning `1.1.1.1` app. You _probably_ want an actual VPN, or you can wait as [CloudFlare seems to be working on a Mac App of their own](https://twitter.com/dok2001/status/1078140619330146304). I'm not certain that `NEVPN` provides the level of service on macOS that something like this really needs, hence why I didn't take it further (there's ways to make DNS lookups bypass it, and I feel like this would be more widespread on some older programs than people realize...).

If you (or anyone) wanted to use this as a base to tinker/modify/release/fork/etc, be my guest. Happy to answer questions further if I can help, but I'll probably close this as I'm not personally looking to work on this further.

Also, for what's it worth, glad I'm not the only one who searched for this kind of thing, lol...

**Comment by goesredy** [comment]
Can you please provide a compiled app for Mojave ?

Thanks
